/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

import recommended from './configs/recommended';
import componentpropertyusereadonly from './rules/component-property-use-readonly';
import denyconstructordi from './rules/deny-constructor-di';
import denyelement from './rules/deny-element';
import denyoverlaycreate from './rules/deny-overlay-create';
import denysoftprivatemodifier from './rules/deny-soft-private-modifier';
import implementsioniclifecycle from './rules/implements-ionic-lifecycle';
import initializetimezoneatmodulescope from './rules/initialize-timezone-at-module-scope';
import ionicattrtypecheck from './rules/ionic-attr-type-check';
import nocomponentmethodexceptlifecycle from './rules/no-component-method-except-lifecycle';
import nocomponentwritablesignal from './rules/no-component-writable-signal';
import noimplicittimezone from './rules/no-implicit-timezone';
import noreactiveforms from './rules/no-reactive-forms';
import notemplatedrivenforms from './rules/no-template-driven-forms';
import noviewmodelsubscribe from './rules/no-viewmodel-subscribe';
import preferdisablehandler from './rules/prefer-disable-handler';
import preferionicstandalone from './rules/prefer-ionic-standalone';
import prefermodallauncher from './rules/prefer-modal-launcher';
import requireionerrortext from './rules/require-ion-error-text';
import requireionitemgroup from './rules/require-ion-item-group';
import requireviewmodel from './rules/require-viewmodel';
import restricttryblock from './rules/restrict-try-block';
import signaluseassignaltemplate from './rules/signal-use-as-signal-template';
import signaluseassignal from './rules/signal-use-as-signal';

export = {
  configs: {
    recommended,
  },
  rules: {
    'component-property-use-readonly': componentpropertyusereadonly,
    'deny-constructor-di': denyconstructordi,
    'deny-element': denyelement,
    'deny-overlay-create': denyoverlaycreate,
    'deny-soft-private-modifier': denysoftprivatemodifier,
    'implements-ionic-lifecycle': implementsioniclifecycle,
    'initialize-timezone-at-module-scope': initializetimezoneatmodulescope,
    'ionic-attr-type-check': ionicattrtypecheck,
    'no-component-method-except-lifecycle': nocomponentmethodexceptlifecycle,
    'no-component-writable-signal': nocomponentwritablesignal,
    'no-implicit-timezone': noimplicittimezone,
    'no-reactive-forms': noreactiveforms,
    'no-template-driven-forms': notemplatedrivenforms,
    'no-viewmodel-subscribe': noviewmodelsubscribe,
    'prefer-disable-handler': preferdisablehandler,
    'prefer-ionic-standalone': preferionicstandalone,
    'prefer-modal-launcher': prefermodallauncher,
    'require-ion-error-text': requireionerrortext,
    'require-ion-item-group': requireionitemgroup,
    'require-viewmodel': requireviewmodel,
    'restrict-try-block': restricttryblock,
    'signal-use-as-signal-template': signaluseassignaltemplate,
    'signal-use-as-signal': signaluseassignal,
  },
};
